-- Generated by build_sql_package.py. Synthetic data, snapshot 2026-09-21.
-- Creates database sale_analytics, schema raw, 12 tables; loads the CSVs from /tmp/sale_analytics; checks row counts.
-- Run with psql (see LOAD_INSTRUCTIONS.md). Safe to re-run.
\set ON_ERROR_STOP on
SELECT 'CREATE DATABASE sale_analytics' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'sale_analytics')\gexec
\c sale_analytics
SET client_min_messages = warning;

CREATE SCHEMA IF NOT EXISTS raw;
DROP TABLE IF EXISTS raw.marketing_spend;
DROP TABLE IF EXISTS raw.arr_monthly;
DROP TABLE IF EXISTS raw.forecast_submissions;
DROP TABLE IF EXISTS raw.opportunity_field_history;
DROP TABLE IF EXISTS raw.opportunities;
DROP TABLE IF EXISTS raw.leads;
DROP TABLE IF EXISTS raw.workspace_usage_monthly;
DROP TABLE IF EXISTS raw.workspaces;
DROP TABLE IF EXISTS raw.accounts;
DROP TABLE IF EXISTS raw.quotas;
DROP TABLE IF EXISTS raw.sales_reps;
DROP TABLE IF EXISTS raw.fx_rates;

CREATE TABLE raw.fx_rates (
    "currency" CHAR(3) NOT NULL,
    "rate_to_eur" NUMERIC(9,4) NOT NULL,
    CONSTRAINT pk_fx_rates PRIMARY KEY (currency)
);
COPY raw.fx_rates FROM '/tmp/sale_analytics/fx_rates.csv' WITH (FORMAT csv, HEADER true);

CREATE TABLE raw.sales_reps (
    "rep_id" VARCHAR(18) NOT NULL,
    "rep_name" VARCHAR(100) NOT NULL,
    "role" VARCHAR(40) NOT NULL,
    "segment" VARCHAR(20) NOT NULL,
    "region" VARCHAR(30) NOT NULL,
    "manager_id" VARCHAR(18),
    "hire_date" DATE NOT NULL,
    "termination_date" DATE,
    "is_active" BOOLEAN NOT NULL,
    CONSTRAINT pk_sales_reps PRIMARY KEY (rep_id)
);
COPY raw.sales_reps FROM '/tmp/sale_analytics/sales_reps.csv' WITH (FORMAT csv, HEADER true);

CREATE TABLE raw.quotas (
    "rep_id" VARCHAR(18) NOT NULL,
    "fiscal_quarter" CHAR(7) NOT NULL,
    "quota_start_date" DATE NOT NULL,
    "ramp_pct" NUMERIC(4,2) NOT NULL,
    "quota_eur" NUMERIC(18,2) NOT NULL,
    CONSTRAINT pk_quotas PRIMARY KEY (rep_id, fiscal_quarter)
);
COPY raw.quotas FROM '/tmp/sale_analytics/quotas.csv' WITH (FORMAT csv, HEADER true);

CREATE TABLE raw.accounts (
    "account_id" VARCHAR(18) NOT NULL,
    "account_name" VARCHAR(200) NOT NULL,
    "website_domain" VARCHAR(100) NOT NULL,
    "industry" VARCHAR(100),
    "employee_count" INT,
    "segment" VARCHAR(20) NOT NULL,
    "billing_country" VARCHAR(60) NOT NULL,
    "region" VARCHAR(30) NOT NULL,
    "annual_revenue_eur" NUMERIC(18,2) NOT NULL,
    "created_date" DATE NOT NULL,
    CONSTRAINT pk_accounts PRIMARY KEY (account_id)
);
COPY raw.accounts FROM '/tmp/sale_analytics/accounts.csv' WITH (FORMAT csv, HEADER true);

CREATE TABLE raw.workspaces (
    "workspace_id" VARCHAR(20) NOT NULL,
    "account_id" VARCHAR(18),
    "signup_date" DATE NOT NULL,
    "hosting_type" VARCHAR(30) NOT NULL,
    "signup_source" VARCHAR(40) NOT NULL,
    "telemetry_enabled" BOOLEAN NOT NULL,
    "owner_email_domain" VARCHAR(100) NOT NULL,
    "is_active" BOOLEAN NOT NULL,
    "churned_month" DATE,
    CONSTRAINT pk_workspaces PRIMARY KEY (workspace_id)
);
COPY raw.workspaces FROM '/tmp/sale_analytics/workspaces.csv' WITH (FORMAT csv, HEADER true);
CREATE INDEX ix_workspaces_account_id ON raw.workspaces (account_id);

CREATE TABLE raw.workspace_usage_monthly (
    "month" DATE NOT NULL,
    "workspace_id" VARCHAR(20) NOT NULL,
    "plan" VARCHAR(30) NOT NULL,
    "executions" BIGINT,
    "active_workflows" INT,
    "active_users" INT,
    "ai_node_executions" BIGINT,
    "distinct_integrations_used" INT,
    "failed_execution_rate" NUMERIC(6,4),
    "self_serve_mrr_eur" NUMERIC(10,2) NOT NULL,
    CONSTRAINT pk_workspace_usage_monthly PRIMARY KEY (workspace_id, month)
);
COPY raw.workspace_usage_monthly FROM '/tmp/sale_analytics/workspace_usage_monthly.csv' WITH (FORMAT csv, HEADER true);
CREATE INDEX ix_workspace_usage_monthly_month ON raw.workspace_usage_monthly (month);

CREATE TABLE raw.leads (
    "lead_id" VARCHAR(18) NOT NULL,
    "created_date" DATE NOT NULL,
    "lead_source" VARCHAR(50) NOT NULL,
    "account_id" VARCHAR(18),
    "workspace_id" VARCHAR(20),
    "email_domain" VARCHAR(100),
    "pql_rule_v1_flag" BOOLEAN NOT NULL,
    "status" VARCHAR(50) NOT NULL,
    "converted_opportunity_id" VARCHAR(18),
    "converted_date" DATE,
    "owner_id" VARCHAR(18),
    CONSTRAINT pk_leads PRIMARY KEY (lead_id)
);
COPY raw.leads FROM '/tmp/sale_analytics/leads.csv' WITH (FORMAT csv, HEADER true);
CREATE INDEX ix_leads_account_id ON raw.leads (account_id);
CREATE INDEX ix_leads_workspace_id ON raw.leads (workspace_id);
CREATE INDEX ix_leads_converted_opportunity_id ON raw.leads (converted_opportunity_id);

CREATE TABLE raw.opportunities (
    "opportunity_id" VARCHAR(18) NOT NULL,
    "opportunity_name" VARCHAR(200) NOT NULL,
    "account_id" VARCHAR(18) NOT NULL,
    "opportunity_type" VARCHAR(30) NOT NULL,
    "lead_source" VARCHAR(50),
    "owner_id" VARCHAR(18) NOT NULL,
    "created_date" DATE NOT NULL,
    "close_date" DATE NOT NULL,
    "stage_name" VARCHAR(40) NOT NULL,
    "forecast_category" VARCHAR(20),
    "amount" NUMERIC(18,2),
    "currency" CHAR(3) NOT NULL,
    "is_closed" BOOLEAN NOT NULL,
    "is_won" BOOLEAN NOT NULL,
    "loss_reason" VARCHAR(60),
    "primary_competitor" VARCHAR(40),
    "primary_workspace_id" VARCHAR(20),
    "next_step" VARCHAR(200),
    "last_activity_date" DATE NOT NULL,
    CONSTRAINT pk_opportunities PRIMARY KEY (opportunity_id)
);
COPY raw.opportunities FROM '/tmp/sale_analytics/opportunities.csv' WITH (FORMAT csv, HEADER true);
CREATE INDEX ix_opportunities_account_id ON raw.opportunities (account_id);
CREATE INDEX ix_opportunities_owner_id ON raw.opportunities (owner_id);
CREATE INDEX ix_opportunities_close_date ON raw.opportunities (close_date);

CREATE TABLE raw.opportunity_field_history (
    "history_id" VARCHAR(18) NOT NULL,
    "opportunity_id" VARCHAR(18) NOT NULL,
    "field" VARCHAR(40) NOT NULL,
    "old_value" VARCHAR(255),
    "new_value" VARCHAR(255),
    "created_by" VARCHAR(18) NOT NULL,
    "created_at" TIMESTAMP(0) NOT NULL,
    CONSTRAINT pk_opportunity_field_history PRIMARY KEY (history_id)
);
COPY raw.opportunity_field_history FROM '/tmp/sale_analytics/opportunity_field_history.csv' WITH (FORMAT csv, HEADER true);
CREATE INDEX ix_opportunity_field_history_opportunity_id_field_created_at ON raw.opportunity_field_history (opportunity_id, field, created_at);

CREATE TABLE raw.forecast_submissions (
    "submission_week" DATE NOT NULL,
    "fiscal_quarter" CHAR(7) NOT NULL,
    "rep_id" VARCHAR(18) NOT NULL,
    "closed_won_qtd_eur" NUMERIC(18,2) NOT NULL,
    "commit_call_eur" NUMERIC(18,2) NOT NULL,
    "best_case_call_eur" NUMERIC(18,2) NOT NULL,
    "open_pipeline_in_quarter_eur" NUMERIC(18,2) NOT NULL,
    CONSTRAINT pk_forecast_submissions PRIMARY KEY (rep_id, submission_week)
);
COPY raw.forecast_submissions FROM '/tmp/sale_analytics/forecast_submissions.csv' WITH (FORMAT csv, HEADER true);

CREATE TABLE raw.arr_monthly (
    "month" DATE NOT NULL,
    "account_id" VARCHAR(18) NOT NULL,
    "arr_eur" NUMERIC(18,2) NOT NULL,
    "new_arr_eur" NUMERIC(18,2) NOT NULL,
    "expansion_arr_eur" NUMERIC(18,2) NOT NULL,
    "contraction_arr_eur" NUMERIC(18,2) NOT NULL,
    "churned_arr_eur" NUMERIC(18,2) NOT NULL,
    "usage_overage_revenue_eur" NUMERIC(18,2) NOT NULL,
    "total_executions" BIGINT NOT NULL,
    CONSTRAINT pk_arr_monthly PRIMARY KEY (account_id, month)
);
COPY raw.arr_monthly FROM '/tmp/sale_analytics/arr_monthly.csv' WITH (FORMAT csv, HEADER true);
CREATE INDEX ix_arr_monthly_month ON raw.arr_monthly (month);

CREATE TABLE raw.marketing_spend (
    "month" DATE NOT NULL,
    "channel" VARCHAR(50) NOT NULL,
    "region" VARCHAR(30) NOT NULL,
    "spend_eur" NUMERIC(18,2) NOT NULL,
    CONSTRAINT pk_marketing_spend PRIMARY KEY (month, channel, region)
);
COPY raw.marketing_spend FROM '/tmp/sale_analytics/marketing_spend.csv' WITH (FORMAT csv, HEADER true);

ANALYZE;

-- check: every row should say OK
SELECT table_name, expected_rows, loaded_rows,
       CASE WHEN expected_rows = loaded_rows THEN 'OK' ELSE 'MISMATCH' END AS status
FROM (
  SELECT 'fx_rates' AS table_name, 3 AS expected_rows, (SELECT count(*) FROM raw.fx_rates) AS loaded_rows
UNION ALL   SELECT 'sales_reps', 36, (SELECT count(*) FROM raw.sales_reps)
UNION ALL   SELECT 'quotas', 187, (SELECT count(*) FROM raw.quotas)
UNION ALL   SELECT 'accounts', 9140, (SELECT count(*) FROM raw.accounts)
UNION ALL   SELECT 'workspaces', 24000, (SELECT count(*) FROM raw.workspaces)
UNION ALL   SELECT 'workspace_usage_monthly', 212783, (SELECT count(*) FROM raw.workspace_usage_monthly)
UNION ALL   SELECT 'leads', 26367, (SELECT count(*) FROM raw.leads)
UNION ALL   SELECT 'opportunities', 4200, (SELECT count(*) FROM raw.opportunities)
UNION ALL   SELECT 'opportunity_field_history', 43045, (SELECT count(*) FROM raw.opportunity_field_history)
UNION ALL   SELECT 'forecast_submissions', 1617, (SELECT count(*) FROM raw.forecast_submissions)
UNION ALL   SELECT 'arr_monthly', 9114, (SELECT count(*) FROM raw.arr_monthly)
UNION ALL   SELECT 'marketing_spend', 1983, (SELECT count(*) FROM raw.marketing_spend)
) x ORDER BY table_name;

-- sanity: won bookings by quarter in EUR
SELECT to_char(o.close_date, 'YYYY') || '-Q' || to_char(o.close_date, 'Q') AS fiscal_quarter,
       count(*) AS deals_won, round(sum(o.amount * fx.rate_to_eur)) AS bookings_eur
FROM raw.opportunities o JOIN raw.fx_rates fx ON fx.currency = o.currency
WHERE o.is_won GROUP BY 1 ORDER BY 1;
